# Generated by Django 5.0 on 2024-01-21 10:13

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure', models.TextField(verbose_name='Գաղտնիության քաղաքականություն')),
                ('offset', models.TextField(verbose_name='փոխհատուցման քաղաքականություն')),
                ('pay', models.TextField(verbose_name='Վճարման համակարգ')),
                ('infos', models.TextField(verbose_name='Ընկերության տվյալներ')),
                ('place', models.TextField(verbose_name='Գտնվելու վայրը')),
                ('connect', models.TextField(verbose_name='Ինչպես միանալ')),
            ],
        ),
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Site name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None, verbose_name='Phone')),
                ('emailname', models.EmailField(max_length=254, verbose_name='Email Name')),
                ('emaillink', models.URLField(null=True, verbose_name='Email url')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook link')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram link')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram link')),
                ('main_icon', models.ImageField(upload_to='icons_imagers', verbose_name='Kayqi Nkar')),
            ],
            options={
                'verbose_name': 'Main Information',
                'verbose_name_plural': 'Main Information',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ապրանքի տեսակ')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='Govazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Սեղեկություններ')),
                ('img', models.ImageField(upload_to='govazd', verbose_name='Նկար')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Կայքի անվանում')),
                ('shortinfo', models.TextField(verbose_name='Կարճ տեղեկություն')),
                ('longinfo', models.TextField(verbose_name='ամբողջական տեղեկություն')),
                ('img', models.ImageField(upload_to='carousel media', verbose_name='Imagers')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='AllProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='products imagers', verbose_name='Գլխավոր նկար')),
                ('img1', models.ImageField(null=True, upload_to='products imagers', verbose_name='Նկար ')),
                ('img2', models.ImageField(null=True, upload_to='products imagers', verbose_name='Նկար ')),
                ('name', models.CharField(max_length=100, verbose_name='Անվանում')),
                ('price_old', models.IntegerField(verbose_name='Գին')),
                ('price_now', models.IntegerField(default=0, verbose_name='Գինը զեղջված')),
                ('dt', models.DateField(auto_now_add=True, null=True)),
                ('info', models.TextField(max_length=250, null=True, verbose_name='Տեղեկություն')),
                ('dissave', models.BooleanField(default=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productr', to='main.category')),
            ],
            options={
                'verbose_name': 'Ապրանք',
                'verbose_name_plural': 'Ապրանքներ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allproductmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('img', models.ImageField(upload_to='comment_imagers', verbose_name='imagers')),
                ('rate', models.IntegerField(null=True, verbose_name='rate')),
                ('datenow', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentr', to='main.allproductmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prouduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saver', to='main.allproductmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_icon', models.ImageField(upload_to='icons_imagers', verbose_name='User icon')),
                ('emailname', models.EmailField(max_length=254, null=True, verbose_name='Email Name')),
                ('emaillink', models.URLField(null=True, verbose_name='Email url')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook link')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram link')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superuser',
                'verbose_name_plural': 'Superusers',
            },
        ),
        migrations.AddField(
            model_name='allproductmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='only', to='main.userinfos'),
        ),
    ]
